tmtc-c2a/Cargo.toml

[rust-embed](https://github.com/pyrossh/rust-embed) はデフォルト挙動では debug build 時に embed せず，実行場所からの相対パスのディレクトリを読み込む（そうか？）．
> In `debug` and when `debug-embed` feature is not enabled, the folder path is resolved relative to where the binary is run from.
しかし，#33 の目的は単に commit された静的アセットの埋め込みを行いたいわけではなく，ビルド済みの C2A DevTools フロントエンドのコードをバイナリに埋め込こみ，C2A Boom ツールチェーンの配布をシンプルにするためであり，C2A DevTools は基本的に常に埋め込みを行いたい．
そのため，`rust-embed` crate の `debug-embed` feature を有効化する．
実行時に読み込みを行いたいユースケースとしては真に C2A DevTools の開発時などが考えられるが，Gaia の開発時 != C2A DevTools の開発時（包含関係ではあるが，常にではない）．埋め込みを行わない場合は C2A DevTools のビルドを別途行わないとフルの動作確認ができないため，C2A DevTools 以外の Gaia の開発時にも実行時に読み込みが走る挙動は非自明かつ冗長となる．
また，現在は（まだバイナリ配布を整備していないこともあり）ビルド速度などのために `cargo install --debug` している箇所が多く，事実上 debug build であっても Gaia の開発が行われているわけではない．

Embed C2A DevTools into tmtc-c2a binary on debug build

---

tmtc-c2a/build.rs

- 現状では，`yarn build` がビルドスクリプトの動作ディレクトリで行われている
- これは基本的にソースファイルのあるディレクトリ
- つまり，開発時のディレクトリや，`~/.cargo/git/checkouts/` 以下など
- これではソースディレクトリがソースファイル以外の状態を持ってしまう
- 開発時のディレクトリで `yarn build` が行われる分には一見あまり影響は無いように思えるが，`~/.cargo/git/checkouts/` 以下などが状態を持つと，リリースしたはずの crate のビルドがべき等ではなくなってしまう
- 具体的には， #60 の前後では前回のビルド時の `node_modules` が `$OUT_DIR/devtools_frontend` にコピーされ，一つ目の `yarn` がコケることがある
- そこで，`devtools_frontend` ディレクトリを `$OUT_DIR` にコピーしてから `yarn`, `yarn build` を行うように変更する

Build C2A DevTools in OUT_DIR

---

Cargo.lock
Cargo.toml
gaia-ccsds-c2a/Cargo.toml
gaia-tmtc/Cargo.toml
tmtc-c2a/Cargo.toml

- `structpack` の内部でのバージョン参照を 0.6 系に変更します（実態としての変更はなし）
- `structpack` など，Gaia 内部の crate の使用バージョンをまとめて管理するため，`workspace.dependencies` にまとめます

Fix internal crate ref version

---

tmtc-c2a/src/main.rs

recorder_hookが使用されていなかったので、option引数としてURIを受け取ってoption_layerをtlm_handlerとcmd_handlerさすようにした。

recorder_layerをoptionで追加

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml
devtools-frontend/Cargo.toml

#68 でライセンス表示をバイナリに埋め込んだので，バイナリ配布を行う．
サポートするプラットフォームは以下
- x86_64-unknown-linux-musl
kble での事例: https://github.com/arkedge/kble/pull/60
現在 C2A user を中心に `tmtc-c2a` を利用している Gaia user が多い．
Gaia ではまだバイナリ配布をしていないため，各所で `cargo install` をするスクリプトを書いている．
例: https://github.com/arkedge/c2a-core/blob/v4.3.0/examples/mobc/tools/install.sh
しかし，Gaia は非常にたくさんのライブラリを用いているため，ビルドが非常に重い．
また，[C2A DevTools](https://github.com/arkedge/c2a-devtools) frontend のホスト（#33）や wasm による [opslang](https://github.com/arkedge/opslang) の導入（#54），[notalawyer](https://github.com/arkedge/notalawyer) の導入（#68）などによって，Gaia のビルドはより複雑かつビルドにあたって要求する環境も変化してきている．
このような重く複雑なビルドを各 C2A user を少し動かしてみるレベルのユーザに要求するのは非現実的であるため，[notalawyer](https://github.com/arkedge/notalawyer) でライセンス表示を行うことでバイナリ配布を実施する．
N/A (internal)

Add release automation workflow for binary distribution

---

.github/workflows/release.yml

#97 で protoc を入れるのを忘れていたので，インストールします
同上
- #97

Install missing protc in release workflow

---

.github/workflows/release.yml

- #98 と同様
- #97 でインストールし忘れていた `wasm-pack` をインストールします
N/A
- #97

Install missing wasm-pack in release workflow

---

.github/workflows/release.yml

#97 でビルド済みバイナリの処理にバグがあったので修正
release workflow でビルドしているバイナリは suffix として target triple を付けているが，`chmod` や GitHub Releases へのファイル添付処理などでそれを加味するのを忘れていた

Fix release binary suffix to wildcard for target triple

---

Cargo.lock
Cargo.toml

SSIA
- おそらく #74 での rebase で間違えた
- `devtools-frontend/crates/wasm-opslang` は `[profile]` の設定をしているが，workspace root 以外ではこれは指定できない
- 実際のビルドにおいては workspace 外で行われる（`pnpm` 経由かつ `OUT_DIR` 内で行われる）ため，この workspace は関係ない
N/A

Exclude c2a-devtools-frontend wasm crates from root Cargo workspace

---

Cargo.lock
Cargo.toml
devtools-frontend/Cargo.toml
gaia-ccsds-c2a/Cargo.toml
gaia-stub/Cargo.toml
gaia-tmtc/Cargo.toml
tmtc-c2a/Cargo.toml

crates.io に publish するため、package.description や package.repository を設定します。
cargo binstall で tmtc-c2a をインストール可能にするためには crates.io への publish が必要であり、crates.io への publish にはそれらのメタデータの設定が必要だからです。

Set crates metadata to publish them

---

.cargo/config.toml
Cargo.lock
Cargo.toml
devtools-frontend/Cargo.toml

crates.io への publish にあたり、workspace 内の crate への参照を path ではなく version による参照にします。
path で参照していると crates.io に publish できないんじゃ。

Fix deps in workspace

---

.github/actionlint.yml

actionlint の self-hosted-runner 用の設定を削除する
actionlint では large runner を使う必要はまったくなく，さらにそもそも現在 large runner を使っていないため
N/A

Bye actionlint large runner

---

devtools-frontend/.prettierignore

`pnpm-lock.yaml` と `devtools-frontend` 内の wasm 用の crate の生成ファイルを `.prettierignore` に入れる
自動生成のファイル群はフォーマットすべきでない
- #111

Fix prettier ignore files

---

.github/workflows/devtools.yml

C2A DevTools フロントエンド用の CI を追加する
- 既にある Rust CI でも内部的にフロントエンドのビルドは行われるが，ログ出力が見づらいので別途ログ出力をしたい
- `cargo build` 経由でのビルドとは別に，フロントエンドの開発時には `devtools-frontend` のソースディレクトリで `pnpm build` することになり，ビルド時の条件が異なるが，こちらも常にビルドできる必要があり，そのチェックをしたい
- そして，#110 ではソースディレクトリ内でのビルドのみ壊れている
- ビルドだけではなく，prettier や eslint などフロントエンド特有の lint もかけたい
- #110

Add C2A DevTools frontend CI workflow

---

.github/workflows/release.yml

現在 `cargo build` などは通るものの `cargo pacakge` が通らないという状況になっている（#108）ため，それを Release workflow 中で検知できるようにする
同上．また， #79 の準備でもある．
- #108

Add cargo package check job in release workflow

---

devtools-frontend/build.rs

`c2a-devtools-frontend` のビルドスクリプトでソースディレクトリを `$OUT_DIR` にコピーする際，`target` も無視するようにする
`cargo package` においては，`cargo build` とビルド時のディレクトリの挙動が異なる．
具体的には，
- ビルド前に workspace の `target/package` 以下にクリーンなビルドをするためソースディレクトリがコピーされる
- この際それぞれの crate のディレクトリを workspace root とするビルドが行われる
- この生成物は `target/package/<crate>-<version>/target` に入る
- ビルドスクリプトが走る前にビルドスクリプト自体のビルドが行われる
- ここで `target/package/<crate>-<version>/target` ができる
- `build.rs` でソースディレクトリを `$OUT_DIR` にコピーする
- この `$OUT_DIR` は `target/package/<crate>-<version>/target` 内
- ここで，`target/package/<crate>-<version>/target` を再帰的にコピーしてしまう
- File name is too long エラーになる
となってしまう．
- #108 
`cargo package` がソースディレクトリを最初にコピーする際，`Cargo.toml` が存在するディレクトリはコピーされない．
このルールは現状 `package.include` などを指定しても bypass できない（正確には `package.license-file` のみ bypass されるが，意図が異なり …

Ignore copy target dir to handle cargo package

---

Cargo.toml
devtools-frontend/crates/Cargo.toml
devtools-frontend/crates/wasm-opslang/Cargo.toml

`devtools-frontend/crates` を cargo workspace にします
WASM 向けの crate の管理は，以下の理由から Gaia 本体の cargo workspace とは別途管理すべきです．
- ビルドターゲットが異なる
- Gaia 本体のビルドターゲットは x86_64 や aarch64 である一方で，このディレクトリ内の crate のビルドターゲットは確実に WASM です
- 一般的なベストプラクティスとして，想定するビルドターゲットが大きく異なる crate は別の cargo workspace で管理すべきです
- 具体的には，workspace root dir で `cargo build` するとどのターゲット向けに何をビルドすべきなのかが非常に非自明になる上に，想定と異なるターゲット向けにビルドされる可能性を考慮しなければならなくなり，不毛です
- WASM 向けのビルドにおいてはバイナリサイズを気にする必要があるため
- `[profile.release]` などを設定したくなりますが，これは workspace root でないと効果を発揮しない設定です
- #117 では `wasm-opslang` crate を workspace root にする提案をしましたが，実用上は個々の WASM 向け crate の profile を個別にチューニングするようなケースは無いものと思われるため，この PR ではよりシンプルに `devtools-frontend/crates` を cargo workspace としています
- `wasm-pack` が呼び出す `cargo metadata` のため
- WASM 向け crate のビルドで用いられる `wasm-pack` …

Add cargo workspace for devtools-frontend WASM

---

.github/workflows/devtools.yml
.github/workflows/rust.yml
.github/workflows/rustdoc.yml

`cargo install` でインストールしている cargo subcommand がキャッシュされていないので修正します
同上
N/A

Fix cache cargo subcommand install

---

.github/workflows/release.yml
.github/workflows/rust.yml
.github/workflows/rustdoc.yml

SSIA
Rust 向けの workflow においても，`tmtc-c2a` の `cargo build` 内で `devtools-frontend` のビルドが行われるため，NodeJS のセットアップをしておく必要がある．
`setup-node` をせずともデフォルトで NodeJS 18 が使えるが，`devtools-frontend` では NodeJS 21 を期待しており，warning が出る．
この修正は `cargo clippy` や `cargo test`, `cargo doc` などを行う分にはそこまで必要ではないが，NodeJS のバージョン起因の問題があった際に調査を容易にするため，また，Release workflow においては，実際に配布するバイナリのビルドを行う workflow であるため，統一して想定されている NodeJS 21 のセットアップを行う．
N/A

Setup NodeJS 21 in Rust workflows for integrated frontend build

---

devtools-frontend/crates/wasm-opslang/Cargo.toml

エラーメッセージ改善のためopslangのバージョンを上げる

Update opslang to 0.2.1

---

devtools-frontend/package.json

SSIA
- #74 で `devtools-frontend` のパスが変更されてから、Protobuf のコード生成のパスが誤ったものになっていたのを修正する
- #74

Fix devtools-frontend protobuf codegen path

---

devtools-frontend/crates/wasm-opslang/Cargo.toml
devtools-frontend/crates/wasm-opslang/build.rs

`wasm-opslang` crate を `cargo build` したら内部で `wasm-pack build` するようにする
- `wasm-pack` のビルド生成物を Cargo のパッケージ管理に載せるため
- `devtools-frontend` のみを Cargo のパッケージ管理に載せていると、`cargo package` できなくなる（https://github.com/arkedge/gaia/pull/112 ）
- Cargo の build script はビルド前に走る処理しか記述できないので、`build.rs` 内に `wasm-pack` 相当の処理を載せることはできない（https://github.com/rustwasm/wasm-pack/issues/251 ）
- そこで、wasm のビルドは確実にビルドターゲットが異なる（まだこの世には wasm32 のマシンは存在しないし、存在してもそこで Gaia をビルドしたい理由は現状存在しない）という性質に着目した
- つまり、`$TARGET` が `wasm32` でないときに `build.rs` 内部で `wasm-pack` を呼び出してビルドする
- 注意: wasm 向けの crate が x86_64 向けや aarch64 向けにも形の上ではビルドできる必要がある
- これは現状の `wasm-opslang` では何も問題なくできる
- 問題が発生したとしても、あくまで形の上でだけビルドできればよいので、`cfg` で対応可能
- `package.links` を用いて、dependents crate （の `build.rs`）に `$OUT_DIR` を渡す
- #108

Invoke wasm-pack in wasm crate build script to package wasm into $OUT_DIR

---

Cargo.lock
devtools-frontend/Cargo.toml
devtools-frontend/build.rs

#127 で `wasm-opslang` crate 内でビルドした wasm ファイルなどを `devtools-frontend` の  `cargo build` 内で使う
- `cargo package` のとき、ソースディレクトリ内に `Cargo.toml` が存在すると問答無用でコピー対象から外れてしまう（#120 ）
- このため、`devtools-frontend` crate 内で wasm の crate をビルドするのは無理がある
- そこで、 #127 で `wasm-opslang` crate 内で wasm のビルドまでを行い、`$OUT_DIR` に出力するようにした
- `wasm-opslang` crate 内でビルドした wasm ファイルなどを `devtools-frontend` crate の `build.rs` 内で vite から扱えるディレクトリ構造にコピーして使う
- これで `devtools-frontend` crate 内で `wasm-pack build` をする必要が無くなったため、そのロジックを削除
- #108

Use dependency output wasm in cargo build

---

devtools-frontend/crates/opslang-wasm/build.rs

`opslang-wasm` crate が `cargo package` できるようにする
- #132 の時点だと、`opslang-wasm` crate で `cargo package` すると `Cargo.lock` が（`target/package` 中の）ソースディレクトリ中に発生してしまい、エラーになってしまう
- この問題の素朴な解決策としては `opslang-wasm` のソースディレクトリを（x86_64/aarch64 ビルドの）`$OUT_DIR` 内にコピーしてそのディレクトリ内で `wasm-pack build` することが考えられる
- しかし（！）`cargo package` の時は `Cargo.toml` の `version.workspace = true` などを解決済みの `Cargo.toml` がソースディレクトリ中に存在するが、通常の `cargo build` などの時についてはそうではない
- そのため、`cargo build` の時は、`version.workspace = true` などが未解決のままの（workspace member であるはずの）ソースディレクトリ一式が `$OUT_DIR` に単独でコピーされ、ビルドに使われる
- このビルドは workspace root のものとして走るので、`version.workspace = true` などを解決できずビルドに失敗してしまう
- そこで（！！！）`wasm-pack build` の後、発生してしまったソースディレクトリ中の `Cargo.lock` を `build.rs` 中で削除することにした
- ついでに `wasm-opslang` のビルドロジックについてコメントを追加
- #108

Fix opslang-wasm packaging

---

Cargo.toml
devtools-frontend/Cargo.toml
devtools-frontend/crates/Cargo.toml
devtools-frontend/crates/opslang-wasm/Cargo.toml
gaia-stub/Cargo.toml
gaia-tmtc/Cargo.toml
structpack/Cargo.toml
tmtc-c2a/Cargo.toml

crate のライセンス定義を cargo workspace を使ってまとめる
基本的に MPL-2.0 で統一しており、いちいち書くのは面倒なため。
今後このリポジトリ内で別のライセンスを付ける crate があった場合においても、その crate についてのみ別個に記述すればよいだけなので問題はない。
- #132 のリリースのため

Merge crate license to cargo workspace

---

devtools-frontend/crates/opslang-wasm/Cargo.toml

バージョン指定が `*` になっている dependency があったので修正します。
`*` 指定だと cargo publish できないため。
https://github.com/arkedge/gaia/issues/108

Specify async-recursion version explicitly

---

tmtc-c2a/src/kble_gs.rs

kble_gsのWebSocket接続がgracefulに終了した場合、uplink側はコマンド待ちで終了せず、downlink側はエラーを吐かないため、（次のコマンドが送られてきてsendに失敗するまで）joinから抜けられない
したがってjoinをselectに変更する
また、終了時に`sink.clone()`することでWebSocketの接続をgracefulに終了する

kble_gsをWebSocketのgracefulな終了に対応させる

---

.github/workflows/rust.yml

Rust CI の `cargo clippy` および `cargo test` を `--locked` オプション付きでチェックする
`--locked` でないと検知できない `Cargo.lock` を更新すべきタイミングなどがあるため
- #140 のマージ後に `Cargo.lock` の未更新エラーが出た

[CI] cargo clippy & test with --locked

---

gaia-ccsds-c2a/src/ccsds/aos/m_pdu.rs
gaia-ccsds-c2a/src/ccsds_c2a/aos/virual_channel.rs
gaia-tmtc/src/recorder.rs
tmtc-c2a/src/kble_gs.rs
tmtc-c2a/src/registry/cmd.rs

ライブラリの更新等で発生していた warning を解決します。

Resolve warnings

---

renovate.json

renovate.json の設定を調整します。
`http` crate が `http-grpc` から漏れていたので追加します。
最新の `axum` v0.7 系は、他の多くの crate と非互換な依存関係を持っているので、当面の間 v0.6 系の最後のバージョンである v0.6.20 に固定します。

Tweak renovate.json

---

renovate.json

tokio-tungstenite を tonic v0.11 と互換性のあるバージョンに固定します。
https://github.com/hyperium/tonic/issues/1579 という事情があり、tonic は hyper 1.0 や axum 0.7 系の世界に追従するのに苦戦している。
当面は hyper 0.14 や axum 0.6 系でやっていく。
関連: https://github.com/arkedge/gaia/pull/164
通らなくて困っているビルドがある PR: https://github.com/arkedge/gaia/pull/159

Pin tokio-tungstenite to compatible version with tonic 0.11

---

renovate.json

http crate のバージョンを tonic 0.11 と互換性のあるバージョンに固定します。
#164 #167 と同様の変更

Pin http to version compatible with tonic 0.11

---

devtools-frontend/crates/opslang-wasm/src/lib.rs

warnings をひとまず無視します。
opslang-wasm において、RuntimeError のいくつかの variant に unused field があるという warn が出ていた。
これらは見かけ上 unused であるが、Debug 用に必要なので残すべきものだと判断し、`allow(dead_code)` とした。
```
warning: field `0` is never read
--> devtools-frontend/crates/opslang-wasm/src/lib.rs:21:19
|
21 |     ParseIntError(std::num::ParseIntError),
|     ------------- ^^^^^^^^^^^^^^^^^^^^^^^
|     |
|     field in this variant
```
@kobkaz この修正でいいですかね？　もしベターな修正案などあればお願いします。

Suppress warns

---

.github/workflows/release.yml
.github/workflows/rust.yml
.github/workflows/rustdoc.yml
tmtc-c2a/Cargo.toml
tmtc-c2a/build.rs
tmtc-c2a/src/lib.rs
tmtc-c2a/src/main.rs

tmtc-c2aをライブラリとして使いたいが、wasm-packやcargo-aboutがないとビルドできないのは不便なので、これらへの依存なしでビルドできるようにする

make devtools/binary dependency optional

---

gaia-ccsds-c2a/Cargo.toml

ref: https://github.com/arkedge/c2a-tlmcmddb/issues/112

Pin tlmcmddb to v2.5.1 because v2.6.1 brakes compatibility

---

devtools-frontend/src/components/CommandView.tsx

暗黙の型変換は望ましくないので、将来的になくすことを前提に警告を表示する

Devtools: show warning popup on auto type conversion

---

devtools-frontend/src/components/OldCommandView.tsx

わかりにくいエラーメッセージを修正
tiが絡んだときに
> Error: the number of parameters is wrong: expected 2, but got 2
のようなエラーメッセージが出ていた

devtools: improve error message
